version: '3.4'

services:
  psychic-pets:
    build:
      context: .
      dockerfile: PsychicPets/Dockerfile
    ports:
      - "80:80"
    environment:
      ConnectionStrings__DefaultConnection: "Server=psychic-pets-db;Database=PsychicPetsDb;User=sa;Password=pizzaPizza!"

  psychic-pets-db:
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
      SA_PASSWORD: "pizzaPizza!"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    volumes:
      - db-data:/var/opt/mssql

volumes:
  db-data:


