version: '3.8'
services:
  sql-server-container:
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=pizzaPizza!
    ports:
      - "1433:1433"
    networks:
      - psychic-pets-network

  psychic-pets:
    build:
      context: .
      dockerfile: Psychic/Dockerfile
    ports:
      - "8080:80"
    environment:
      ConnectionStrings__DefaultConnection: "Server=sql-server-container;Database=PsychicPetsDb;User=sa;Password=pizzaPizza!"
    depends_on:
      - sql-server-container
    networks:
      - psychic-pets-network

networks:
  psychic-pets-network:


